variables:
  GIT_DEPTH: 1
  IMAGE_NAME: lucaferrera/flask-geolocalization
  CONTAINER_NAME: test_container

stages:
  - test
  - package

.docker-job: &docker_job
  image: docker:latest

  variables:
    REMOTE_IMAGE_NAME: /${IMAGE_NAME}

pytest:
  stage: test
  script:
  - apt install pytest -y
  - export PYTHONPATH="$PWD"
  - pytest
  


docker-build-branches:
  stage: package

  <<: *docker_job

  script:
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
    - docker run --rm -d ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}

  only:
    - branches

  except:
    - master
    - tags

docker-build-latest:
  stage: package

  <<: *docker_job

  script:
    - docker pull ${IMAGE_NAME}:latest
    - docker run --rm -d ${IMAGE_NAME}


  only:
    - master
    - tags
