variables:
  GIT_DEPTH: 1
  IMAGE_NAME: lucaferrera/flask-geolocalization

stages:
  - test
  - package


.docker-job: &docker_job
  image: docker:latest

  variables:
    REMOTE_IMAGE_NAME: hub.docker.com/repository/docker/${IMAGE_NAME}


docker-build-branches:
  stage: package

  <<: *docker_job

  script:
    - docker pull ${IMAGE_NAME}:latest
    - docker run --rm -d -p 5000:5000 ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}

  only:
    - branches

  except:
    - master
    - tags

docker-build-latest:
  stage: package

  <<: *docker_job

  script:
    - docker pull ${IMAGE_NAME}:latest
    - docker run --rm -d -p 5000:5000 ${IMAGE_NAME} 


  only:
    - master
    - tags
