image: python:3.6.9-stretch

variables:
  GIT_DEPTH: 1
  IMAGE_NAME: lucaferrera/flask-geolocalization
  CONTAINER_NAME: test_container

stages:
  - test
  - package

pytest:
  stage: test
  script: 
    - pip install -r requirements.txt
    - export PYTHONPATH="$PWD"
    - pytest


.docker-job: &docker_job
  image: docker:latest

  variables:
    REMOTE_IMAGE_NAME: /${IMAGE_NAME}
  
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}


docker-build-branches:
  stage: package

  <<: *docker_job

  script:
    - docker build --build-arg COMMIT_SHA=${CI_COMMIT_SHA} --pull -t ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} .
    - docker run --rm -d ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}

  only:
    - branches

  except:
    - master
    - tags

docker-build-latest:
  stage: package

  <<: *docker_job

  script:
    - docker build --build-arg COMMIT_SHA=${CI_COMMIT_SHA} --pull -t ${IMAGE_NAME} .
    - docker run --rm -d ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}
    - docker save ${IMAGE_NAME}:latest -o latest.tar.gz

  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - latest.tar.gz


  only:
    - master
    - tags
